[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "blue>=0.9.1",
    "mypy>=1.1.1",
    "isort>=5.12.0",
    "pytest>=7.2.2",
]

[project]
name = "np_pipeline_qc"
version = "0.0.1"
description = ""
authors = [
    {name = "corbennett", email = "corbettb@alleninstitute.org"},
    {name = "bjhardcastle", email = "ben.hardcastle@alleninstitute.org"},
]
dependencies = [
    "np-session>=0.4.25",
    "pandas>=1.5.3",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
